# Rubocop rules explanation:
#  https://github.com/rubocop-hq/rubocop/blob/master/config/default.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 3.0.3
  NewCops: enable
  Exclude:
    - bin/bundle
    - spec

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Style/ExpandPathArguments:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Metrics/MethodLength:
  Max: 50

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25
